name: Semgrep SAST for HTML

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Semgrep SAST scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/owasp-top-ten"  # This rule set is a good start for web vulnerabilities (XSS, SQLi, etc.)
